### ISSUE TITLE
Python implementation?

### ISSUE THREAD

**Issue by jtlz2** [fj86/PoissonBinomial#2]
I am looking for a python implementation of the Generalized PBD - is this something you might be able to assist with?

Thanks so much for any and all assistance

**Comment by DISOhda** [comment]
Hello,

Unfortunately, I do not use Python in my daily work, so I forgot almost everything about it. But If I am not mistaken, the transfer of the C++ code of the Direct Convolution and Normal approaches should be straight-forward for an experienced Pythoneer.

Best,
Florian

Von: jtlz2 ***@***.***>
Gesendet: Dienstag, 18. April 2023 10:59
An: DISOhda/PoissonBinomial ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [DISOhda/PoissonBinomial] Python implementation? (Issue #2)


I am looking for a python implementation of the Generalized PBD - is this something you might be able to assist with?

Thanks so much for any and all assistance
